2024-11-03 13:02:52,542 - ERROR - Error loading template: type object 'DocumentGenerator' has no attribute 'config_manager'
2024-11-03 17:03:21,291 - ERROR - Database connection error: 2003 (HY000): Can't connect to MySQL server on 'localhost:3306' (10061)
2024-11-03 17:03:29,052 - ERROR - Database connection error: 2003 (HY000): Can't connect to MySQL server on 'localhost:3306' (10061)
2024-11-03 17:04:15,872 - ERROR - Error loading template: type object 'DocumentGenerator' has no attribute 'config_manager'
2024-11-03 17:28:09,185 - ERROR - Error en la ejecución principal: 'Config' object is not callable
2024-11-03 17:28:41,552 - ERROR - Error loading template: type object 'DocumentGenerator' has no attribute 'config_manager'
2024-11-06 08:09:06,567 - ERROR - Database connection error: 2003 (HY000): Can't connect to MySQL server on 'localhost:3306' (10061)
2024-11-07 11:25:17,446 - ERROR - Database connection error: 2003 (HY000): Can't connect to MySQL server on 'localhost:3306' (10061)
2024-11-07 11:58:18,008 - ERROR - Database connection error: 2003 (HY000): Can't connect to MySQL server on 'localhost:3306' (10061)
2024-11-07 11:58:29,062 - ERROR - Database connection error: 2003 (HY000): Can't connect to MySQL server on 'localhost:3306' (10061)
2024-11-07 11:58:36,529 - ERROR - Database connection error: 2003 (HY000): Can't connect to MySQL server on 'localhost:3306' (10061)
2024-11-07 11:59:48,341 - ERROR - Error loading config: [Errno 2] No such file or directory: 'c:\\Users\\lloyd\\Documents\\entornos virtuales de python\\proyecto_de_python\\proyecto_prueba\\gestor_docs_suiza\\Interfaces\\config.json'
2024-11-07 11:59:48,343 - ERROR - Error loading template: Package not found at 'c:\Users\lloyd\Documents\entornos virtuales de python\proyecto_de_python\proyecto_prueba\gestor_docs_suiza\Interfaces\Interfaces\Plantillas\ASISTENCIA_DIARIA.docx'
2024-11-07 12:00:57,765 - ERROR - Error loading config: [Errno 2] No such file or directory: 'c:\\Users\\lloyd\\Documents\\entornos virtuales de python\\proyecto_de_python\\proyecto_prueba\\gestor_docs_suiza\\Interfaces\\config.json'
2024-11-07 12:00:57,959 - ERROR - Error loading config: [Errno 2] No such file or directory: 'c:\\Users\\lloyd\\Documents\\entornos virtuales de python\\proyecto_de_python\\proyecto_prueba\\gestor_docs_suiza\\Interfaces\\config.json'
2024-11-08 09:43:05,758 - ERROR - Database connection error: 2003 (HY000): Can't connect to MySQL server on 'localhost:3306' (10061)
